apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-{{ include "sickchill.fullname" . }}-1
  labels:
    name: {{ include "sickchill.fullname" . }}-config
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  capacity:
    storage: 20G     
  accessModes:
  - ReadWriteOnce    
  glusterfs:         
    endpoints: gluster-cluster 
    path: fast
    readOnly: false
  persistentVolumeReclaimPolicy: Retain 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slow-{{ include "sickchill.fullname" . }}-1
  labels:
    name: {{ include "sickchill.fullname" . }}-download
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: {{ .Values.persistence.download.storageClass | quote }}
  capacity:
    storage: 50G
  accessModes:
  - ReadWriteOnce    
  glusterfs:         
    endpoints: gluster-cluster 
    path: slow
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slow-{{ include "sickchill.fullname" . }}-2
  labels:
    name: {{ include "sickchill.fullname" . }}-tv
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: {{ .Values.persistence.processed.storageClass | quote }}
  capacity:
    storage: 50G
  accessModes:
  - ReadWriteOnce    
  glusterfs:         
    endpoints: gluster-cluster 
    path: slow
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
     
