{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sickchill.fullname" . }}-config
  labels:
    {{- include "sickchill.labels" . | nindent 4 }}
    component: config
spec:
  accessModes:
  - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
{{- end }}
---
{{- end }}
{{- if .Values.persistence.downloads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sickchill.fullname" . }}-downloads
  labels:
    {{- include "sickchill.labels" . | nindent 4 }}
    component: downloads
spec:
  accessModes:
  - {{ .Values.persistence.downloads.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size | quote }}
{{- if .Values.persistence.downloads.storageClass }}
  storageClassName: {{ .Values.persistence.downloads.storageClass | quote }}
{{- end }}
---
{{- end }}
{{- if .Values.persistence.processed.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "sickchill.fullname" . }}-processed
  labels:
    {{- include "sickchill.labels" . | nindent 4 }}
    component: processed
spec:
  accessModes:
  - {{ .Values.persistence.processed.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.processed.size | quote }}
{{- if .Values.persistence.processed.storageClass }}
  storageClassName: {{ .Values.persistence.processed.storageClass | quote }}
{{- end }}
---
{{- end }}