apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-{{ include "couchpotato.fullname" . }}-1
  labels:
    name: {{ include "couchpotato.fullname" . }}-config
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  capacity:
    storage: 20G     
  accessModes:
  - ReadWriteOnce    
  glusterfs:         
    endpoints: gluster-cluster 
    path: fast
    readOnly: false
  persistentVolumeReclaimPolicy: Retain 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slow-{{ include "couchpotato.fullname" . }}-1
  labels:
    name: {{ include "couchpotato.fullname" . }}-downloads
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: {{ .Values.persistence.downloads.storageClass | quote }}
  capacity:
    storage: 50G
  accessModes:
  - ReadWriteOnce    
  glusterfs:         
    endpoints: gluster-cluster 
    path: slow
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: slow-{{ include "couchpotato.fullname" . }}-2
  labels:
    name: {{ include "couchpotato.fullname" . }}-movies
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  storageClassName: {{ .Values.persistence.processed.storageClass | quote }}
  capacity:
    storage: 50G
  accessModes:
  - ReadWriteOnce    
  glusterfs:         
    endpoints: gluster-cluster 
    path: slow
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
     
