{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "transmission.fullname" . }}-config
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
    component: config
spec:
  accessModes:
  - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
{{- end }}
---
{{- end }}
{{- if .Values.persistence.download.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "transmission.fullname" . }}-download
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
    component: download
spec:
  accessModes:
  - {{ .Values.persistence.download.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.download.size | quote }}
{{- if .Values.persistence.download.storageClass }}
  storageClassName: {{ .Values.persistence.download.storageClass | quote }}
{{- end }}
---
{{- end }}
{{- if .Values.persistence.watch.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "transmission.fullname" . }}-watch
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
    component: watch
spec:
  accessModes:
  - {{ .Values.persistence.watch.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.watch.size | quote }}
{{- if .Values.persistence.watch.storageClass }}
  storageClassName: {{ .Values.persistence.watch.storageClass | quote }}
{{- end }}
---
{{- end }}