# Default values for transmission.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linuxserver/transmission
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.00-r0-ls69"

nameOverride: ""
fullnameOverride: ""

uid: 1000
gid: 1000
tz: UTC
webHome: /combustion-release/

persistence:
  config:
    enabled: false
    storageClass: config
    claimName: ''
    accessMode: ReadWriteOnce
    subPath: ''
    size: 10G
  download:
    enabled: false
    storageClass: download
    claimName: ''
    accessMode: ReadWriteOnce
    subPath: ''
    size: 100G
  watch:
    enabled: false
    storageClass: watch
    claimName: ''
    accessMode: ReadWriteOnce
    subPath: ''
    size: 10G

service:
  type: ClusterIP
  port: 9091

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
